validação ESTRUTURA IF-ELSE
função validaSenha(senha) {
    deixe senhaCorreta = "batataBananaTomate";

    se a senha está CORRETA
    retorna - permitido acesso
 se (senha == senhaCorreta) {
     se FAZ uma ação
     SE a condição dele estar VERDADEIRA
     console. log("permitido acesso");

 } mais {
     se a senha está INCORRETA
    retorna - acesso negado
     console. log("acesso negado");
 }

}

validaSenha("estruturacondicional");
validaSenha("batataBananaTomate");

função validaNovaSenha(senha) {
    deixe senhaCorreta = "thugstools"
    senha de retorno  == senhaCorreta ? console. log("permitido"): console.  log("negado");
}

validaNovaSenha("ifTernario");
validaNovaSenha("thugstools");

exemplo
limite de funçãoDeConsumo(valor) {
retorno valor <= limitePermitido ? aumentarLimite (valor+10) : zerarLimite();
// }