// Quais são as variáveis? Quais são as constantes? De que tipo são? Qual variável
// poderia armazenar o valor null segundo estes dados?

/*O Índice de Massa Corporal (IMC) se calcula dividindo o peso pela altura2

(a altura
deve estar em metros e o peso em quilogramas). Por exemplo, no caso de Carlos
de Souza, a altura ao quadrado é 3,09.
Você deverá criar 6 variáveis:
● Nome
● Idade
● Peso
● Altura
● Plano (só nos interessa saber se TEM ou NÃO TEM)
● Índice de Massa Corporal (IMC)
O programa deverá apresentar em tela o valor do IMC de um paciente da tabela
com uma mensagem. Por exemplo: “Aline Ferreira tem 33 anos e seu índice de massa
corporal é de xx”.*/

let nome = "GILVAN";
let Idade = 46;
let Peso = 80.1;
let Altura = 1.76;
let plano = true;

console.log ((Altura**2)/Peso);

console.log((176**2)/80);

var IMC =(176**2)/80;

console.log(IMC);
