let nome = "jose da Silva";
let idade = 27;
let peso = 8.5;
let altura = 1.70;
let plano = true;
const IMC = (peso / altura*altura);


{
      console.log(nome,"tem",idade,"anos","e seu índice de massa corporal é de",IMC)
}

  // console.log(nome, "tem",idade)


// let nomex = "jose da Silva";
// let idadex = 17;{
//     console.log(nomex,idadex);
// }

// let nomexa = "jose da silva";{
//     console.log(nomexa);
// }

// let nomex = "Danilo";
// let idadex = 30;

// console.log(nomex);

// function testar(){
//     let nomex = "ANA";
//     return console.log(nomex);
// }
// testar();
// console.log(nomex);

//********************************************************** */

// let nomea = "Gilvan";
// let idadea = 46;

// console.log(nomea);

// function testar(){
//     let nomea = "livia";
//     return console.log(nomea);
// }

// testar();
// console.log(nomea);

