//Declare uma variável com o nome status. Atribua a ela um valor booleano: (true ou false).
//Em seguida, faça um if que avalie o valor contido nesta variável. Se o valor armazenado for 
//true, imprima a seguinte mensagem no console: O valor é true - verdadeiro. Caso contrário,
// imprima a mensagem: O valor é false - falso.

let status = true{
    if (status == true ){
        console.log ("O valor é true - verdadeiro")};
        else{
            console.log("O valor é false - falso");
        }
    
// CODIGO DE CONDICAO

let dia = "Domingo";

if(dia == "Domingo"){
    console.log("Vou para praia");}
    else{
        console.log("fico em casa");}

// CODIGO IF ELSE

let dia = "Domingo";
  if(dia == "Domingo"){
     console.log("Vou para praia");
     else if(dia == "Sexta"){
         console.log("vou para o cinema");
     else if( dia == "Segunda"){
         console.log("vou ficar em casa");    
     }
      else{
      console.log("fico em casa");
    }