function dividir(a,b){
    return a/b;
}

console.log("divisao",dividir(4,2));

console.log("**************pulalinha*****************");

function multiplicar(a,b){
        return a*b;
}

console.log('multiplicao',multiplicar(8,5));

console.log("**************pulalinha*****************");

function quadradoDoNumero(a){
    return multiplicar(a,a);
}

console.log('quadradonumero',quadradoDoNumero(7))

console.log("**************pulalinha*****************");



