// EXERCICIO CALCULADORA AULA 6
// IDENTIFICACAO, C0METNTARI EM LINHA
// COMENTARIO EM BLOCO
//* COMENTARIO EM BLOCO PARA DOCUMENTACAO , NAO E MUITO UTILIZADO EM JS VERIFICAR QUAL O CONTEXTO **/
// CRIAR FUNCAO E QUEBRA EM VARIOS PROBLEMAS, //

function adicionar(a, b) {
    let soma = a + b;
    console.log("funcao adicionar -", soma)
    return soma;
}

console.log(adicionar(1, 4));

//*somar = adicionar(1,1);*//
//* console.log("mostrar somar - " + somar);

function adicionar(a, b) {
    let soma = a + b;
    // console.log("funcao adicionar -", soma)
    return soma;
}

// somar = function adicionar (a, b) {


/*exemplo
function subtrair(valorproduto, valorrecebido){
    // valorproduto = 100
    // valorrecebido = 50
    return valorrecebido-valorproduto; 
}
*/

function subtrair(a, b) {
    return a - b;
}

console.log(subtrair(1, 4));

// valor multiplicacao do exercicio 

function multiplicar(a, b) {
    return a * b;
}

console.log(multiplicar(5, 3));

// valor dividir do exercicio

function dividir(a, b) {
    return a / b;
}

console.log(dividir(4, 2));

// function quadradodonumero

function quadradodonumero(a) {
    return multiplicar(a, a)

}

console.log(multiplicar(5, 2));
console.log




