//funcao declarada
function daroi (){
    console.log("ola tudo bem?")

}

daroi();
daroi();
daroi();

// funcao expresa usar uma variavel let, var
// pode colocar parametros que fica dentro do parenteses ex let somar = function(PARAMETRO) sempre coloca virgula

let somar = function(){
    console.log(1+1);
}

somar();

//

let somar1 = function(numA, numB){
    console.log(numA+numB);
}

somar1(1,2);


//IMPORTANTE////IMPORTANTE////
// QUANDO QUER QUE APARECA A FUNÇÃO FORA DE OUTRA FUNCAO COLOCAR RETURN

let somar1 = function(numA, numB){
    console.log(numA+numB);

let resultado = soma(1, 2){

    console.log(numA+numB);
}

resultado(1,2);