// valor not a number nan

let naoNumerico = NaN;
    console.log(naoNumerico);

    let jogadores = null;
    console.log(jogadores);

let espectadores = undefined;
espectadores = 10;
    console.log(espectadores);

    // objetivo literal 
    // criando um objeto
    // dois pontos :coloca a atribuição

    let = moto = {
        marca : "honda", 
        ano: " 1995",
    }

    console.log (moto);



// array
// . conjunto de dados , arrays é por posiçoes

let series = [
"friends","todo mundo odeia cris"];

console.log(series);