//ADICAO 

console.log (2+2);

console.log (10-1);

console.log (10*3);

console.log (10/2);

// incremento no final com console.log depois

let numero = 10;
console.log(numero++);
console.log(numero);

// incremento no comeco do codigo
let numero1 = 14;
console.log(++numero1);


// dercremento

let numero21 = 155;
console.log(--numero21);

// COMPARACAO RIGOROSO

// COMPARACAO MAIOR

console.log (10>5);

// COMPARACAO Menor
console.log(10<5);

console.log(3<=3);

console.log(5>=10);

// comparacao igualdade

console.log(10 == 20);

console.log("ola" == "ola");

// comparacao rigososa
console.log(5 === "5");

// comparacao diferenca !=

console.log (10 != 10);

console.log ("ola"!= "oi");

// diferenca rigida

console.log(10 !== "10");

// comparador logico && E AND
console.log(10 >5 && 11>5);

// comparador logico || OR

console.log(10 > 5 || 11 > 5);

// COMPRADOR DE NEGACO ! como ele nega, faz ao contrato da verdade

console.log(!5 < 1) 

let nome = "gilvan";
let sobrenome ="fonseca"

console.log(nome + " " + sobrenome);